from __future__ import annotations

from enum import Enum


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class EnvelopeState(str, Enum):
    CLOSED = "CLOSED"
    OPENING = "OPENING"
    OPEN = "OPEN"
    CLOSING = "CLOSING"


class ContinuationSignal(str, Enum):
    NONE = "NONE"
    HOLD_ELIGIBLE = "HOLD_ELIGIBLE"
    REDUCE_CANDIDATE = "REDUCE_CANDIDATE"
    MODIFY_CANDIDATE = "MODIFY_CANDIDATE"
    EXIT_CANDIDATE = "EXIT_CANDIDATE"


class EventType(str, Enum):
    RETURN_SHAPE_UPDATED = "RETURN_SHAPE_UPDATED"
    ENVELOPE_CONTEXT_UPDATED = "ENVELOPE_CONTEXT_UPDATED"
    CAPTURABILITY_EVALUATED = "CAPTURABILITY_EVALUATED"
    APERTURE_UPDATED = "APERTURE_UPDATED"
    ENVELOPE_OPENING = "ENVELOPE_OPENING"
    ENVELOPE_OPENED = "ENVELOPE_OPENED"
    ENVELOPE_CLOSING = "ENVELOPE_CLOSING"
    ENVELOPE_CLOSED = "ENVELOPE_CLOSED"
    QUALIFIED_OPPORTUNITY = "QUALIFIED_OPPORTUNITY"
    HOLD_ELIGIBLE = "HOLD_ELIGIBLE"
    REDUCE_CANDIDATE = "REDUCE_CANDIDATE"
    MODIFY_CANDIDATE = "MODIFY_CANDIDATE"
    EXIT_CANDIDATE = "EXIT_CANDIDATE"
    DATA_INVALID = "DATA_INVALID"
    MARKET_INELIGIBLE = "MARKET_INELIGIBLE"
    SHAPE_EXPIRED = "SHAPE_EXPIRED"
